name: 'J-dogcoder labels Action'
description: 'Import the labels @J-dogcoder uses in his projects'
inputs:
  github-token:
    description: 'GitHub token for repo'
    required: true
  owner-name:
    description: 'Onwer name is user or organisation'
    required: true
  repository-name:
    description: 'GitHub repo name'
    required: true
  icon: check
  color: black
runs:
  using: "composite"
  steps:
    - name: 'install dependency'
      run: npm install github-label-template
      shell: bash
    - name: 'import labels from json file'
      run: npx ghlbl -o ${{ inputs.owner-name }} -r ${{ inputs.repository-name }} -t ${{ inputs.github-token }} -i ${{ github.action_path }}/labels.json
      shell: bash
